#!/usr/bin/env python
# -*- coding: utf-8 -*-

# "THE WISKEY-WARE LICENSE":
# <utn_kdd@googlegroups.com> wrote this file. As long as you retain this notice 
# you can do whatever you want with this stuff. If we meet some day, and you
# think this stuff is worth it, you can buy us a WISKEY us return.


#===============================================================================
# DOCS
#===============================================================================

"""Launcher of yatel gui client

"""

#===============================================================================
# IMPORTS
#===============================================================================

from yatel import gui


#===============================================================================
# FUNCTION
#===============================================================================

def main():
    """Run a yatel qt app client
    
    """
    gui.run_gui()


#===============================================================================
# MAIN
#===============================================================================

if __name__ == "__main__":
    main()
